name: Build Electron App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
      env:
        CI: false
        
    - name: Build React app
      run: |
        npm run build
      env:
        CI: false
        
    - name: Copy electron.js to build directory
      run: |
        Copy-Item -Path "public\electron.js" -Destination "build\electron.js" -Force
        
    - name: Build Electron app
      run: |
        npm run electron:build
      env:
        CI: false
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/*.exe
