name: Build and Release Electron App

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install --force
      
    - name: Generate app icon
      run: npm run generate-icon
        
    - name: Build React app
      run: npm run react-build
      env:
        CI: false
        
    - name: Build Windows exe
      run: npm run build:win
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-builds
        path: |
          dist/*.exe
          dist/win-unpacked/**/*
        if-no-files-found: error
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
